// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoarWCOzan03FbBEPLIpJheRUysBXlRg0',
    appId: '1:217277512573:web:fede9740721bb67996aa14',
    messagingSenderId: '217277512573',
    projectId: 'guardian-tap-76134',
    authDomain: 'guardian-tap-76134.firebaseapp.com',
    storageBucket: 'guardian-tap-76134.appspot.com',
    measurementId: 'G-YFZTMG84VS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD93PoGllcwx7gg7VFDNe7vs_otalBN938',
    appId: '1:217277512573:android:6faed27b07f8fc3396aa14',
    messagingSenderId: '217277512573',
    projectId: 'guardian-tap-76134',
    storageBucket: 'guardian-tap-76134.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC92fvOFhFBBUwHa-dsf7k8uS4Yt1ttpEE',
    appId: '1:217277512573:ios:af808eba205c41bd96aa14',
    messagingSenderId: '217277512573',
    projectId: 'guardian-tap-76134',
    storageBucket: 'guardian-tap-76134.appspot.com',
    iosBundleId: 'com.example.guardiantap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC92fvOFhFBBUwHa-dsf7k8uS4Yt1ttpEE',
    appId: '1:217277512573:ios:5aa596537243032796aa14',
    messagingSenderId: '217277512573',
    projectId: 'guardian-tap-76134',
    storageBucket: 'guardian-tap-76134.appspot.com',
    iosBundleId: 'com.example.guardiantap.RunnerTests',
  );
}
